import 'dart:async';
import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:http/http.dart' as http;
import 'package:shared_preferences/shared_preferences.dart';

const apiBaseUrl = String.fromEnvironment('API_BASE_URL', defaultValue: 'http://10.0.2.2:8000');
const platform = MethodChannel('espero_cbt/security');

void main() => runApp(const CbtApp());

class ApiClient {
  ApiClient(this.prefs);
  final SharedPreferences prefs;
  String? get token => prefs.getString('token');
  Map<String, String> get headers => {'Accept': 'application/json', 'Content-Type': 'application/json', if (token != null) 'Authorization': 'Bearer $token'};
  Future<Map<String, dynamic>> post(String path, Map<String, dynamic> body) async => _decode(await http.post(Uri.parse('$apiBaseUrl$path'), headers: headers, body: jsonEncode(body)));
  Future<Map<String, dynamic>> get(String path) async => _decode(await http.get(Uri.parse('$apiBaseUrl$path'), headers: headers));
  Map<String, dynamic> _decode(http.Response r) { if (r.statusCode >= 400) throw Exception(jsonDecode(r.body)['message'] ?? r.body); return jsonDecode(r.body) as Map<String, dynamic>; }
}

class CbtApp extends StatefulWidget { const CbtApp({super.key}); @override State<CbtApp> createState() => _CbtAppState(); }
class _CbtAppState extends State<CbtApp> { SharedPreferences? prefs; @override void initState(){super.initState(); SharedPreferences.getInstance().then((p)=>setState(()=>prefs=p));} @override Widget build(BuildContext context)=>MaterialApp(title:'Espero CBT', theme:ThemeData(colorSchemeSeed:Colors.blue), home:prefs==null?const Scaffold(body:Center(child:CircularProgressIndicator())):LoginPage(api:ApiClient(prefs!))); }

class LoginPage extends StatefulWidget { const LoginPage({super.key, required this.api}); final ApiClient api; @override State<LoginPage> createState()=>_LoginPageState(); }
class _LoginPageState extends State<LoginPage> { final u=TextEditingController(), p=TextEditingController(); bool busy=false; String? err; Future<void> login() async { setState(()=>busy=true); try { final device = await platform.invokeMapMethod<String,dynamic>('deviceInfo') ?? {'device_id':'unknown'}; final res=await widget.api.post('/api/v1/auth/login', {'username':u.text,'password':p.text,...device}); await widget.api.prefs.setString('token', res['token']); if(mounted) Navigator.pushReplacement(context, MaterialPageRoute(builder:(_)=>DashboardPage(api:widget.api))); } catch(e){setState(()=>err='$e');} finally{setState(()=>busy=false);} } @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Login Siswa')),body:Padding(padding:const EdgeInsets.all(16),child:Column(children:[TextField(controller:u,decoration:const InputDecoration(labelText:'Username')),TextField(controller:p,decoration:const InputDecoration(labelText:'Password'),obscureText:true),if(err!=null)Text(err!,style:const TextStyle(color:Colors.red)),const SizedBox(height:12),FilledButton(onPressed:busy?null:login,child:Text(busy?'Masuk...':'Login'))]))); }

class DashboardPage extends StatefulWidget { const DashboardPage({super.key, required this.api}); final ApiClient api; @override State<DashboardPage> createState()=>_DashboardPageState(); }
class _DashboardPageState extends State<DashboardPage>{ List exams=[]; @override void initState(){super.initState(); load();} Future<void> load() async { final r=await widget.api.get('/api/v1/student/exams'); setState(()=>exams=r['data']??[]);} @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('Daftar Ujian')),body:RefreshIndicator(onRefresh:load,child:ListView(children:exams.map((e)=>ListTile(title:Text(e['nama_ujian']),subtitle:Text('${e['mata_pelajaran']} • ${e['tanggal_ujian']}'),trailing:const Icon(Icons.chevron_right),onTap:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>TokenPage(api:widget.api,exam:e))))).toList())));}

class TokenPage extends StatelessWidget { TokenPage({super.key, required this.api, required this.exam}); final ApiClient api; final Map exam; final token=TextEditingController(); Future<void> start(BuildContext context) async { final device=await platform.invokeMapMethod<String,dynamic>('deviceInfo')??{'device_id':'unknown'}; final r=await api.post('/api/v1/student/exams/${exam['id']}/start', {'token':token.text.toUpperCase(), ...device}); if(context.mounted) Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>ExamPage(api:api,result:r['session']))); } @override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(exam['nama_ujian'])),body:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('Instruksi: jangan keluar aplikasi, jangan screenshot, dan pastikan koneksi stabil.'),TextField(controller:token,decoration:const InputDecoration(labelText:'Token Ujian')),FilledButton(onPressed:()=>start(c),child:const Text('Mulai Ujian'))]))); }

class ExamPage extends StatefulWidget { const ExamPage({super.key, required this.api, required this.result}); final ApiClient api; final Map result; @override State<ExamPage> createState()=>_ExamPageState(); }
class _ExamPageState extends State<ExamPage> with WidgetsBindingObserver { List qs=[]; int index=0; Timer? heartbeat; String save=''; @override void initState(){super.initState(); WidgetsBinding.instance.addObserver(this); _secure(); load(); heartbeat=Timer.periodic(const Duration(seconds:15),(_)=>widget.api.post('/api/v1/student/sessions/${widget.result['id']}/heartbeat',{}).catchError((_){}));} Future<void> _secure() async { await platform.invokeMethod('enableExamMode', {'orientation': 'portrait'}); } @override void dispose(){heartbeat?.cancel(); WidgetsBinding.instance.removeObserver(this); platform.invokeMethod('disableExamMode'); super.dispose();} @override void didChangeAppLifecycleState(AppLifecycleState state){ if(state!=AppLifecycleState.resumed){ logCheat('app_${state.name}'); }} Future<void> logCheat(String type) async { if(mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text('Peringatan pelanggaran: $type'))); await widget.api.post('/api/v1/student/sessions/${widget.result['id']}/cheating-log', {'type':type}).catchError((_){ }); } Future<void> load() async { final r=await widget.api.get('/api/v1/student/sessions/${widget.result['id']}/questions'); setState(()=>qs=r['questions']); } Future<void> answer(String key) async { setState(()=>save='Menyimpan...'); await widget.api.post('/api/v1/student/sessions/${widget.result['id']}/answer', {'question_id':qs[index]['id'],'jawaban':key}); setState(() { qs[index]['answer']=key; save='Tersimpan'; }); } Future<void> submit() async { await widget.api.post('/api/v1/student/sessions/${widget.result['id']}/submit',{}); if(mounted) Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const FinishedPage())); } @override Widget build(BuildContext c){ if(qs.isEmpty) return const Scaffold(body:Center(child:CircularProgressIndicator())); final q=qs[index]; return PopScope(canPop:false,child:Scaffold(appBar:AppBar(title:Text('Soal ${index+1}/${qs.length}'),automaticallyImplyLeading:false),body:SelectionArea(enabled:false,child:Padding(padding:const EdgeInsets.all(16),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Text(q['soal'],style:const TextStyle(fontSize:18)),const SizedBox(height:12),...List<Map>.from(q['options']).map((o)=>RadioListTile(value:o['key'],groupValue:q['answer'],onChanged:(v)=>answer(v!),title:Text(o['text']))),Text(save),Wrap(children:List.generate(qs.length,(i)=>Padding(padding:const EdgeInsets.all(2),child:OutlinedButton(onPressed:()=>setState(()=>index=i),child:Text('${i+1}'))))),const Spacer(),Row(children:[OutlinedButton(onPressed:()=>widget.api.post('/api/v1/student/sessions/${widget.result['id']}/flag', {'question_id':q['id'],'is_flagged':!(q['is_flagged']??false)}),child:const Text('Ragu-ragu')),const Spacer(),FilledButton(onPressed:submit,child:const Text('Submit'))])]))))); }}
class FinishedPage extends StatelessWidget { const FinishedPage({super.key}); @override Widget build(BuildContext c)=>const Scaffold(body:Center(child:Text('Ujian selesai.'))); }
